-- Migration: 002_create_trades_table.sql
-- Description: Creates the trades table for storing individual trade records
-- Created: 2026-01-15

CREATE TYPE trade_direction AS ENUM ('long', 'short');
CREATE TYPE trade_status AS ENUM ('open', 'closed', 'cancelled');

CREATE TABLE IF NOT EXISTS trades (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    model_id UUID NOT NULL REFERENCES models(id) ON DELETE CASCADE,
    symbol VARCHAR(20) NOT NULL,
    direction trade_direction NOT NULL,
    entry_price DECIMAL(20, 8) NOT NULL,
    exit_price DECIMAL(20, 8),
    quantity DECIMAL(20, 8) NOT NULL,
    entry_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    exit_time TIMESTAMP WITH TIME ZONE,
    status trade_status NOT NULL DEFAULT 'open',
    pnl DECIMAL(20, 8),
    pnl_percentage DECIMAL(10, 4),
    fees DECIMAL(20, 8) NOT NULL DEFAULT 0,
    slippage DECIMAL(20, 8),
    signal_confidence DECIMAL(5, 4),
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Indexes for common queries
CREATE INDEX idx_trades_model_id ON trades(model_id);
CREATE INDEX idx_trades_symbol ON trades(symbol);
CREATE INDEX idx_trades_status ON trades(status);
CREATE INDEX idx_trades_direction ON trades(direction);
CREATE INDEX idx_trades_entry_time ON trades(entry_time);
CREATE INDEX idx_trades_exit_time ON trades(exit_time);
CREATE INDEX idx_trades_model_entry_time ON trades(model_id, entry_time);

-- Trigger to automatically update updated_at
CREATE TRIGGER update_trades_updated_at
    BEFORE UPDATE ON trades
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Trigger to calculate PnL when trade is closed
CREATE OR REPLACE FUNCTION calculate_trade_pnl()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.exit_price IS NOT NULL AND NEW.status = 'closed' THEN
        IF NEW.direction = 'long' THEN
            NEW.pnl = (NEW.exit_price - NEW.entry_price) * NEW.quantity - NEW.fees;
            NEW.pnl_percentage = ((NEW.exit_price - NEW.entry_price) / NEW.entry_price) * 100;
        ELSE
            NEW.pnl = (NEW.entry_price - NEW.exit_price) * NEW.quantity - NEW.fees;
            NEW.pnl_percentage = ((NEW.entry_price - NEW.exit_price) / NEW.entry_price) * 100;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER calculate_trades_pnl
    BEFORE UPDATE ON trades
    FOR EACH ROW
    EXECUTE FUNCTION calculate_trade_pnl();

COMMENT ON TABLE trades IS 'Stores individual trade records generated by models';
COMMENT ON COLUMN trades.model_id IS 'Reference to the model that generated this trade';
COMMENT ON COLUMN trades.symbol IS 'Trading pair symbol (e.g., BTC-USD)';
COMMENT ON COLUMN trades.direction IS 'Trade direction: long (buy) or short (sell)';
COMMENT ON COLUMN trades.entry_price IS 'Price at which the position was entered';
COMMENT ON COLUMN trades.exit_price IS 'Price at which the position was exited';
COMMENT ON COLUMN trades.quantity IS 'Size of the position';
COMMENT ON COLUMN trades.pnl IS 'Profit/Loss in quote currency';
COMMENT ON COLUMN trades.pnl_percentage IS 'Profit/Loss as a percentage';
COMMENT ON COLUMN trades.signal_confidence IS 'Model confidence score for the trade signal (0-1)';
